# Generated by Django 4.2.6 on 2024-01-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_alter_tournamentplayer_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentplayer',
            name='discord_avatar',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='discord_global_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='discord_user_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='discord_username',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='osu_user_id',
            field=models.BigIntegerField(),
        ),
    ]
