# Generated by Django 4.2.6 on 2024-02-13 21:46
from django.contrib.auth.models import User
from django.db import migrations, models
from userauth.models import TournamentPlayer


def get_staff_status(apps, schema_editor):
    tournament_player_model: TournamentPlayer = apps.get_model('userauth', 'TournamentPlayer')
    django_auth_user: User = apps.get_model('auth', 'User')
    db_alias = schema_editor.connection.alias

    staff_users = django_auth_user.objects.filter(is_staff=True)
    tournament_player_model.objects.using(db_alias).filter(pk__in=staff_users).update(
        is_staff=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0016_tournamentplayer_is_captain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(get_staff_status, reverse_code=migrations.RunPython.noop)
    ]
