# Generated by Django 4.2.6 on 2024-02-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0017_tournamentplayer_is_staff'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tournamentplayer',
            index=models.Index(fields=['is_staff'], name='userauth_to_is_staf_40d222_idx'),
        ),
    ]
